name: deploy-client
on:
  push:
    branches:
      - main
    paths:
      - "client/**"
jobs:
  build_and_delploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: Building files
        run: |
          cd client
          npm i
          npm run build

      - name: Generate SSH key
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > ~/secret.pem
          chmod 600 ~/secret.pem

      - name: Copy build files
        run: |
          scp -o StrictHostKeyChecking=accept-new -i "~/secret.pem" -r client/dist/** ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:client

      - name: SSH into EC2 instance and restarting server
        run: |
          ssh -i "~/secret.pem" ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} '
          pm2 restart client
          '
